name: 'ecomm_analytics'
version: '1.0.0'
config-version: 2

profile: 'ecomm'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"
  - "logs"

models:
  ecomm_analytics:
    staging:
    intermediate:
    mart:

tests:
  ecomm_analytics:
    warn_canceled_orders_with_delivery:
      +severity: warn
    error_excessive_canceled_with_delivery:
      +severity: error    
