ecomm:
  target: duckdb  # Default to DuckDB
  outputs:
    duckdb:
      type: duckdb
      path: /app/duckdb/analytics.duckdb
      threads: 4
      extensions:
        - parquet
      settings:
        TimeZone: 'UTC'
    
    snowflake:
      type: snowflake
      account: "{{ env_var('SNOWFLAKE_ACCOUNT') }}"
      user: "{{ env_var('SNOWFLAKE_USER') }}"
      private_key_path: /root/.ssh/snowflake_key
      role: ACCOUNTADMIN
      database: ECOMM_ANALYTICS
      warehouse: COMPUTE_WH
      schema: RAW
      threads: 4